Happy Thoughts Emelie Svensson
Technigo/project-happy-thoughts pull request #102
Opened 2020-10-31 14:10 UTC by emeliesv

Link to my deployed project:
https://epic-northcutt-bbbe21.netlify.app/

My reflections on how this week's project turned out:
This week I've done the blue requirements and I'm satisfied with that. I'm glad that I have a working page to show, which is responsive.

2020-11-03 19:26 UTC, sarahejhej requested changes
Hello!

Well done this week! It was a lot to learn this week and I'm very impressed that you managed to put all fetches in the app component. 

General feedback is to remove all unnecessary comments, console.logs and unused components and class rules. Also, if someone types a really long word then the styling will break. It is easy to fix by adding `word-break: break-word;`to your thought cards! 💯🥳

2020-11-03 19:26 UTC, sarahejhej commented on code/src/components/Thoughts.js
> +    empty string then move it to a new array, which then the map.() iterates over*/
Maybe this could also be removed or changed to something more descriptive

2020-11-03 19:26 UTC, sarahejhej commented on code/src/components/Thoughts.js
> +        <div className="thoughts__container">{thoughts.filter((thought) => thought.message !== undefined).map((thought) => {
This filter function could be removed to the (GET) fetch function in App.js!

2020-11-03 19:26 UTC, sarahejhej commented on code/src/components/Thoughts.js
> +                        <p className="thoughts__message">{thought.message}</p>
Same class name on different tags

2020-11-03 19:26 UTC, sarahejhej commented on code/src/components/Thoughts.js
> +})  */
This could be removed!

2020-11-03 19:26 UTC, sarahejhej commented on code/src/components/app.css
> +    grid-template-columns: repeat(3, 1fr);
Not sure why there are three columns. When looking at the page the content is not centered, so maybe one column would be enough and then add rows for every thought post

2020-11-03 19:26 UTC, sarahejhej commented on code/src/components/footer.js
> +import React from 'react'
This is never mounted so it could be removed!

2020-11-03 19:26 UTC, sarahejhej commented on code/src/components/header.css
> +    align-self: center;
These two could be removed!

2020-11-03 19:26 UTC, sarahejhej commented on code/src/components/input.css
> +    flex-wrap: wrap;
Don't think you need to wrap the container

2020-11-03 19:26 UTC, sarahejhej commented on code/src/components/input.css
> +    align-content: center;
This could be removed also

2020-11-03 19:26 UTC, sarahejhej commented on code/src/components/input.css
> +    max-width: 100%;
With textarea you could specify number of rows directly in the JSX

2020-11-03 19:26 UTC, sarahejhej commented on code/src/components/thoughts.css
> +}
I now see that you made this container into a grid. Maybe it would be easier and less code if the grid for the whole page was specified in app__grid

2020-11-03 19:26 UTC, sarahejhej commented on code/src/components/thoughts.css
> +.thoughts__info-container, .thoughts__message-and-like {
No need for separate class names if the styling is the same. Also .thoughts__message-and-like is never used

2020-11-03 19:26 UTC, sarahejhej commented on code/src/components/thoughts.css
> +/*How to solve when someone writes a really long word?*/
I know! You can break a word by adding `word-break: break-word;`

2020-11-10 17:55 UTC, EmOlsz commented on code/src/components/App.js
> +      onMessageChange={saveNewMessage}
Wrong indentations

2020-11-10 17:55 UTC, EmOlsz commented on code/src/components/Input.js
> +        checkIfMessageLengthValid(newMessage) && onMessageChange(newMessage);
Almost correct Sara - variables that store boolean values should be named like `isMessageValid`.
Function like this one could be named `validateMessage`

2020-11-10 17:55 UTC, EmOlsz commented on code/src/components/Thoughts.js
> +                        <p className="thoughts__message">{thought.message}</p>
A bit more styling is needed, right now your website broke a bit when I wrote super long word without any spaces

2021-03-09 11:23 UTC, closed without merging