Agnes happy journal
Technigo/project-happy-thoughts pull request #138
Opened 2020-11-11 13:42 UTC by aagneshansson

Link to my deployed project:
http://stayhappy.netlify.net/

My reflections on how this week's project turned out:

Things I'd like to have clarified or explained in more detail:

2020-11-11 18:34 UTC, evelinabe requested changes
Great job with your happy journal, Agnes! 
I like the structure with components and separate CSS-files. The comments are nice, and just enough to make the code more readable. 

There are two things I'd like you to change. First, your function for disabling button doesn't work as intended due to a spelling mistake. The same goes for the span which should show different colors when the message has the right length. Fix the spelling and it should be good to go!

The second thing is that the text won't break if you write a really, really, really long word. This could be fixed by adding `word-wrap: break-word` in the styling.

2020-11-11 18:34 UTC, evelinabe commented on code/src/HappyForm.css
> +    border: 1px solid black;
Just for consistency you could write the color as `#000` instead of `black`

2020-11-11 18:34 UTC, evelinabe commented on code/src/HappyForm.js
> +                    disabled={message.lenght < 6 || message.lenght > 140 ? true : false}
Spelling mistake here - it should read `.length`.

2020-11-11 18:34 UTC, evelinabe commented on code/src/HappyForm.js
> +                    <span style={{ color: message.lenght < 6 || message.lenght > 140 ? "red" : "#000" }}>
Spelling mistake on `.length` here as well.

2020-11-11 18:34 UTC, evelinabe commented on code/src/HappyForm.css
> +    background: white;
For consistency, color should be `#fff`.

2020-11-11 18:34 UTC, evelinabe commented on code/src/HappyForm.js
> +                valure={message}
Should it be `value`?

2020-11-12 14:35 UTC, EmOlsz commented on code/src/HappyForm.js
> +const Happyform = "https://happy-thoughts-technigo.herokuapp.com/thoughts";
This is not the best name for url variable :

1. First of all, only components should have names written in uppercase
2. Something like `MESSAGE_URL` would be far better

2020-11-12 14:35 UTC, EmOlsz commented on code/src/HappyForm.js
> +                body: JSON.stringify({ message: message }),
Since both left and right side of object has same name, we can simplify it :

```
body: JSON.stringify({ message })
```

2020-11-12 14:35 UTC, EmOlsz commented on code/src/HappyForm.js
> +            .catch(err => console.log("error:", err))
`console.error` would be more appropriate

2021-03-09 11:23 UTC, closed without merging