Happy Thoughts Machine
Technigo/project-happy-thoughts pull request #83
Opened 2020-10-29 13:20 UTC by pwangy

Link to my deployed project: 
https://pwangy-happy.netlify.app/

My reflections on how this week's project turned out: 
One of my goals this week was to finish this project early so I could have dedicated time to rework my portfolio. So I'm happy to have completed the blue level goals AND hit both a red and a black level goal too. This week also felt really good in that a few React concepts are _finally_ starting to make more sense to me through repetitive use in a few different projects. Starting this little app was fun and I think I got really close in cloning the styling of the app too. Then I hit the "Like" button functionality and that was the hardest bit to figure out this week. After struggling with that for a while, I was finally able to make it work. I don't completely understand it, but I think it will make more sense, the more I practice. 

Things I'd like to have clarified or explained in more detail: 
Should we be breaking out our CSS into different files to reflect our components? Does it matter?

2020-11-02 20:36 UTC, MindstormingAB requested changes
Well done Peggy! It was really interesting to dive into your code. You showed a good understanding of the React states and achieved easily the blue requirements. I'm really impressed by your local storage and the local count of likes.
Next time, you could improve readability by creating more components and you could work more on accessibility.
Before I approve your pull request, I'd like you to make sure that the page works on mobile phones.

2020-11-03 11:31 UTC, pwangy commented on code/src/App.js
> +          aria-label="love letter emoji"
added!

2020-11-03 11:33 UTC, pwangy commented on code/.eslintrc.json
>      "semi": "off"
I wish I could! I think this updated when I went through Van's steps to update whatever npm was complaining about.

2020-11-03 11:33 UTC, pwangy commented on README.md
> +- Show a count below the form input that updates as the user types and shows how many characters are remaining. Make it go red when the user has typed over 140 characters
:D

2020-11-03 11:49 UTC, pwangy commented on code/src/index.css
> +  word-break: break-all;
> You should use `word-break: break-word` so you can avoid this
> ![image](https://user-images.githubusercontent.com/32522911/97909479-95064900-1d48-11eb-89a8-633f16a2e5bd.png)

Sandrine, what browser are you using? I haven't been able to reproduce this error on my machine. :(

2021-01-07 12:46 UTC, closed without merging